name: Fam.ly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  infinite_scroll_pagination: ^3.2.0
  icons_launcher: ^2.0.4
  intl: ^0.17.0

  cloud_firestore: ^3.4.9
  # firebase_core: ^1.23.0
  firebase_auth: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/icons/famly-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
